export const MOCK_PACTS = [
  {
    id: '1',
    title: 'Website Redesign Milestone 1',
    category: 'Freelance Escrow',
    stakeAmount: 500,
    currency: 'USDC',
    counterparty: 'alex_dev',
    status: 'Active',
    progress: 65,
    deadline: '2026-03-20T12:00:00Z',
    description: 'Completion of the homepage and navigation components.',
    resolutionMethod: 'Mutual Release',
  },
  {
    id: '2',
    title: 'Gym 3x a Week Challenge',
    category: 'Accountability',
    stakeAmount: 50,
    currency: 'USDC',
    counterparty: 'Pactum Oracle',
    status: 'Active',
    progress: 40,
    deadline: '2026-03-31T23:59:59Z',
    description: 'User must check in at the gym 12 times this month.',
    resolutionMethod: 'External Oracle',
  },
  {
    id: '3',
    title: 'BTC > $100k by April',
    category: 'Prediction',
    stakeAmount: 100,
    currency: 'USDC',
    counterparty: 'Public Pool',
    status: 'Pending',
    progress: 0,
    deadline: '2026-04-01T00:00:00Z',
    description: 'Will Bitcoin reach a new all-time high above $100,000?',
    resolutionMethod: 'External Oracle',
  },
  {
    id: '4',
    title: 'Chess Match vs Grandmaster',
    category: 'Gaming',
    stakeAmount: 25,
    currency: 'USDC',
    counterparty: 'chess_king',
    status: 'Disputed',
    progress: 100,
    deadline: '2026-03-05T18:00:00Z',
    description: 'Winner takes the pot. Dispute raised regarding move 34.',
    resolutionMethod: 'Referee',
    referee: 'magnus_fan',
  },
];

export const MOCK_TRANSACTIONS = [
  {
    id: 'tx1',
    type: 'Deposit',
    amount: 500,
    currency: 'USDC',
    date: '2026-03-01T10:00:00Z',
    pactId: '1',
    status: 'Confirmed',
  },
  {
    id: 'tx2',
    type: 'Deposit',
    amount: 50,
    currency: 'USDC',
    date: '2026-03-02T14:30:00Z',
    pactId: '2',
    status: 'Confirmed',
  },
  {
    id: 'tx3',
    type: 'Payout',
    amount: 200,
    currency: 'USDC',
    date: '2026-02-25T09:15:00Z',
    pactId: 'old-pact-99',
    status: 'Confirmed',
  },
];
